# Generated by Django 3.2.15 on 2022-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_link_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_live',
            field=models.CharField(default='', max_length=100),
        ),
    ]
