# Generated by Django 3.2.15 on 2022-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_link_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_repo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
