# Generated by Django 4.1.4 on 2022-12-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_project_pro_ico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="pro_ico",
            field=models.CharField(max_length=50),
        ),
    ]
