# Generated by Django 4.1.4 on 2022-12-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_project_pro_ico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="pro_ico",
        ),
        migrations.CreateModel(
            name="Tecnoproject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tecno_ico", models.FileField(upload_to="", verbose_name="images/")),
                (
                    "project",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
