# Generated by Django 4.1.4 on 2022-12-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_project_pro_ico_tecnoproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnoproject",
            name="tecno_ico",
            field=models.CharField(max_length=50),
        ),
    ]
