# Generated by Django 4.1.4 on 2022-12-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_tecnoproject_tecno_ico"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tecnoproject",
        ),
    ]
