# Generated by Django 4.1.4 on 2023-02-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="imagen",
            new_name="imagenabout",
        ),
    ]
