# Generated by Django 3.2.18 on 2023-03-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_imagen_about_imagenabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='bio',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
