# Generated by Django 4.1.7 on 2023-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_about_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
