# Generated by Django 4.1.7 on 2023-03-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_technology_project_technologys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="technologys",
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
