# Generated by Django 4.1.7 on 2023-03-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='project',
            field=models.ManyToManyField(related_name='technologys', to='core.project'),
        ),
    ]
