name: Docker Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Pull changes
        run: |
            git pull
      
      - name: Check SSH connectivity
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADRESS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful"
            cd /home/vlopez/portafolio/portfolio-front
            git pull origin master
            echo "Deteniendo contenedores..."
            docker-compose down
            echo "Reconstruyendo contenedores..."
            docker-compose build --no-cache
            echo "Deteniendo contenedores..."
            docker-compose down
            echo "Levantando contenedores con nuevos cambios..."
            docker-compose up -d --remove-orphans
