name: Docker Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Check out code
        run: |
            echo "Checking out code..."
            git status
            git log -1
      - name: Check SSH connectivity
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADRESS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful"
            cd /home/vlopez/portafolio/portfolio-front
            git pull origin master
            echo "Deteniendo los contenedores del backend y frontend..."
            docker-compose stop frontend portafolioback
            echo "Reconstruyendo los contenedores del backend y frontend..."
            docker-compose build --no-cache frontend portafolioback
            echo "Levantando los contenedores del backend y frontend con nuevos cambios..."
            docker-compose up -d --remove-orphans frontend portafolioback


