name: Deploy Portfolio Production

on:
  push:
    branches: [master]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Force update master branch
        run: |
            git fetch --all
            git reset --hard origin/master
            git pull --rebase origin master
      - name: Conectar via ssh y desplegar
        uses: appleboy/ssh-action@master
        
        with:
          host: ${{ secrets.IP_ADRESS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/vlopez/portafolio/portfolio-front
            git fetch --all
            git reset --hard origin/master
            git pull --rebase origin master
            echo "Deteniendo servicios...."
            docker-compose down
            echo " Recontruyendo imagenes y levantando servicios...."
            docker-compose build --no-cache
            docker-compose up -d 
            echo "Servicios levantados correctamente"