name: Docker Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check SSH connectivity
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADRESS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: echo "SSH connection successful"
            cd /home/vlopez/portafolio
            docker-compose build
            echo "Deteniendo contenedores..."
            docker-compose down
            script: echo "SSH connection successful"
            docker-compose up -d --remove-orphans
