name: Deploy Portfolio Production

on:
  push:
    branches: [master]

concurrency:
  group: deploy-portfolio
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP_ADRESS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -Eeuo pipefail
            BRANCH="master"
            APP_DIR="/home/vlopez/portafolio/portfolio-front"
            # Opcional: limitar servicios, ej: SERVICES="frontend"
            # SERVICES=""

            cd "$APP_DIR"
            git fetch --all
            git reset --hard "origin/$BRANCH"

            if docker compose version >/dev/null 2>&1; then
              DC="docker compose"
            else
              DC="docker-compose"
            fi

            if [ -n "${SERVICES:-}" ]; then
              $DC pull $SERVICES || true
              $DC build --no-cache --pull $SERVICES
              $DC up -d --remove-orphans $SERVICES
            else
              $DC pull || true
              $DC build --no-cache --pull
              $DC up -d --remove-orphans
            fi

            echo "Deploy de portafolio completado."